spring:
  flyway:
    schemas: ui_db
  datasource:
    url: jdbc:postgresql://postgresdb-service:5432/postgres?currentSchema=${spring.datasource.hikari.schema}
    username: argen
    password: lampard08
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ui_db
    schema: classpath:db/schema.sql

